### ISSUE TITLE
Don't take others work as your own

### ISSUE THREAD

**Issue by nedbat** [amitassaraf/pdbi#1]
This commit: https://github.com/amitassaraf/pdbi/commit/7006d1d22626b5424386d29955ea93f9605b8edb seems to be trying to deny the authorship of the code. You can't simply remove other people's copyright notices.

**Comment by ciphergoth** [comment]
Ned is correct; what you want to do here is add your name to the list, not remove the existing names. If this notice appears in a lot of files, it can make sense to put this sort of thing in a single COPYRIGHT file and change all the files to point at that, but it's important to retain the original names. Cheers!

**Comment by amitassaraf** [comment]
Are you specifically talking about setup.py? Please tell me where I removed the original names because I never meant to do so!

**Comment by amitassaraf** [comment]
NVM, I am reverting the commit now. Sorry!

**Comment by nedbat** [comment]
Thanks.  Also in the README, and ideally, you'd make pull requests back to the original repo.
